services:
  database:
    container_name: postgres_container
    image: postgres:14.18
    ports:
      - 5000:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: quang  
      POSTGRES_PASSWORD: q
    volumes:
      - ./postgres/data:/var/lib/postgres/data