version: 2

sources:
  - name: wt
    database: weather
    schema: wt
    tables:
     - name: raw_weather_data
       columns:
         - name: id
         - name: city
         - name: temperature
         - name: weather_description
         - name: wind_speed
         - name: inserted_at
         - name: utc_offset